# Configuration for IELTS appointment monitoring

# Base URL for the IELTS website (use 'localhost' for simulation server)
# Options: 'https://irsafam.org/ielts/timetable' (real website) or 'http://localhost:8000' (simulation server)
# base_url: 'https://irsafam.org/ielts/timetable'
# base_url: 'http://localhost:8000'  # Testing with simulation server
base_url: 'http://77.91.84.205:8000/ielts/timetable'  # to test github actions 

cities:
  - isfahan

# Exam models to check (cdielts, pdielts)
exam_models:
  - cdielts

# Months to check (1-12, e.g., 10 for October, 11 for November)
months:
  - 10
  - 11
  - 12
  - 1

# Monitoring frequency in seconds (300 = 5 minutes, recommended for production)
check_frequency: 180

# Show unavailable/filled slots in output
show_unavailable: false

# Disable SSL certificate verification (use with caution)
no_ssl_verify: false
